### ISSUE TITLE
 Concurrent access to attributes is not protected

### ISSUE THREAD

**Issue by SergeAyer** [micjunod/TSM_AES_2023-2024_GG_MJ#8]
In both static_scheduling_with_event::GearDevice and PedalDevice, access to _currentGear and _pedalRotationTime must be protected against concurrent access (by using atomic operations preferably)

**Comment by vocthor** [comment]
resolved [here](https://github.com/micjunod/TSM_AES_2023-2024_GG_MJ/pull/9)
